### ISSUE TITLE
Player cannot jump when near edge

### ISSUE THREAD

**Issue by Rinder5** [this-place/this.place#15]

**Comment by Rinder5** [comment]
currently, we use a raycast from the middle of the controller down with size 1 (half of the object). Possibly it is better with a bounding box, or raycasting from all 4 corners.

**Comment by nicholaschuayunzhi** [comment]
> Possibly it is better with a bounding box, or raycasting from all 4 corners.

I agree too! Would definitely help with removing the magic numbers in https://github.com/this-place/this.place/pull/16/files

**Comment by nicholaschuayunzhi** [comment]
I also found a possibly related bug:

when the player just manages to jump onto a block (some weird clipping at the edge) and the player can't jump.
