### ISSUE TITLE
Final Stretch (demo 16/4 thoughts)

### ISSUE THREAD

**Issue by Rinder5** [this-place/this.place#203]
- [x] Fix camera (zoom keeps getting further)

- [x] Fix disintegrate block (when shooting point-blank, the game dies)

- [x] Fix Stage 2-Part 3 Secondary collectible (game shows 2 but only 1 can be found)

- [x] Fix Stage 3-Part 1 Post-Processing (when jumping off at a specific angle, the post processing disappears)

- [x] End Screen

- [x] Video

- [x] Dim colors of pulled block

- [x] Make Coins Glow

- [x] Make Coins Scale into world

- [x] Fix checkpoint facing (it affects the direction of facing when loading/reloading)

- [x] Reloading sometimes put you in awkward positions

- [ ] Fix stage 2-part 3 to stage 2-part 4 transition being unnatural

**Comment by nicholaschuayunzhi** [comment]
There was issue with stage_2_part_3 to stage_2_part_4 being unnatural. Should we merge them into one scene?

**Comment by Rinder5** [comment]
#208 referenced the remaining outstanding issues, so this issue is no longer needed
