### ISSUE TITLE
Camera rotation up and down

### ISSUE THREAD

**Issue by Rinder5** [this-place/this.place#24]

**Comment by nicholaschuayunzhi** [comment]
Hmm... if we're sticking to the 4 angle rotate, I dont think we need an up and down? And I doubt we want to see underneath the stage 😆

**Comment by Rinder5** [comment]
wait, what are the 4 angles if not left, right, up, down?

**Comment by nicholaschuayunzhi** [comment]
Oh i meant 4 left/right viewing angles. Cycling through them with q and e.

**Comment by Rinder5** [comment]
ok. I put in the pr (#22) anyway, when we next meet up we can test it out and see which one is better.

> And I doubt we want to see underneath the stage 😆

I limited the angle so it can only move up and down a specific amount.

> Oh i meant 4 left/right viewing angles. Cycling through them with q and e

I thought boss wanted it to be freeform though, like the Captain Toad's treasure hunt game
