### ISSUE TITLE
BlockBehaviour#MoveBlock(BlockFaceBehaviour) should allow for acceleration

### ISSUE THREAD

**Issue by nicholaschuayunzhi** [this-place/this.place#34]
Currently if a block is moved twice in the same direction, it does not maintain the acceleration, resulting in blocks falling in constant velocity. Should implement a way to apply acceleration to a moving block when it it is moved again the frame after it has stopped moving.

**Comment by reginleiff** [comment]
May I try to tackle this?

**Comment by nicholaschuayunzhi** [comment]
Yea go ahead. At the same time, you can implement it any logical way you want. EG: change `BlockBehaviour#MoveBlock` to allow more than 1 unit movement. Or setting the flags after translation has ended.
