### ISSUE TITLE
Camera lags behind player

### ISSUE THREAD

**Issue by Rinder5** [this-place/this.place#43]

**Comment by nicholaschuayunzhi** [comment]
Would this be similar to the boom camera in unreal?

**Comment by Rinder5** [comment]
it was part of tutorial 4 i think, don't remember what they called it

**Comment by Rinder5** [comment]
do we still want this?

**Comment by nicholaschuayunzhi** [comment]
Considering we are using 3rd person camera that moves with mouse inputs. I'm not too sure.. @reginleiff ?

How about a camera zoom to prevent object obstruction?

**Comment by Rinder5** [comment]
Closing this to replace with new more related issue.
