### ISSUE TITLE
Level: tutorial stage

### ISSUE THREAD

**Issue by reginleiff** [this-place/this.place#51]
Design and create a tutorial stage. While playing the tutorial, the player should:
- intuitively know what to do next
- be introduced to the controls to the game
- be introduced to the game mechanics, including displace
- be introduced to some types of blocks; namely dirt, stone, sand and gravel
- know about deaths and resetting the game

**Comment by teclu** [comment]
To be done:
- make the level more linear
- add decorative prefabs to it
- link it up with stage 1
