### ISSUE TITLE
Checkpoints for resetting game state

### ISSUE THREAD

**Issue by reginleiff** [this-place/this.place#62]
## Motivation
Although @teclu and I have discussed that we will have invisible walls to prevent the player from dying, the player may desire to return to a certain checkpoint where the puzzle has been untouched. This brings up the question on whether to only allow the player to respawn at the start or at selected points in the stage. Either way, I suggest we have this feature to allow for resetting the stage when resuming the game or on request.

## Deliverables
- [x] Tech: A checkpoint that will gracefully bring the player back from her current location upon request.

- [x] Design: Method of returning should fit with story. Future stage designs should permit a planned entry to a location for checkpoint saving. Alternatively, we could have a checkpoint trigger.

- [x] Art: An animation that facilitates the graceful movement. It could range from a simple graphic that warps the player or something cooler like an animal swooping down to collect her back.

http://gph.to/2G8crEL

**Comment by nicholaschuayunzhi** [comment]
Regarding this, do we have to reset the state of all game blocks? If we don't there may be some "shortcuts" with respawn.

**Comment by saho-london** [comment]
making game effect is completely different from making 3D models. I have to do research first.
