### ISSUE TITLE
Camera snapback to preset angles

### ISSUE THREAD

**Issue by reginleiff** [this-place/this.place#64]
## Motivation
Originally we had the camera to had rotate between four preset angles, but upon playtesting the game during stage design, I realised it could be quite frustrating to leave the camera at the previous view once I had finished the block movements I wanted to make in that specific view. Also, the game did look quite strange at certain angles. 

![image](https://user-images.githubusercontent.com/22815234/37188516-8e802f5c-238a-11e8-8a92-b8c9f57f2271.png)
_* Blue marks a block but it cannot be seen accurately in this view._

## Suggestions
1. We can set a reset camera option to bring it back to the standard initialisation view. 

2. We can bring back the camera rotate about the four preset angles; we can even use this to change lighting and effects based on these preset positions to make sure shadows don't look weird in certain views. In addition, we keep our current implementation of tilt and rotate but the camera will automatically snap back to the previous preset angle after releasing the RMB. 

Its not an important feature so its not very urgent. Also, the latter sounds like a lot of additional work for a minor enhancement.

Any thoughts? @Rinder5 @teclu @jo-lyn

**Comment by Rinder5** [comment]
i don't quite understand the example problem.  Is the issue that the block doesn't look like a block and it transitions into the other block, cause I thought that was what we wanted?

**Comment by Rinder5** [comment]
@reginleiff have you tried the 3rd person camera yet? if that is fine, there's no more "preset" angle to revert to.

**Comment by Rinder5** [comment]
not necessary anymore, due to 3rd person camera letting the player maneuver the camera more freely.
