### ISSUE TITLE
Character does not get pushed off block

### ISSUE THREAD

**Issue by reginleiff** [this-place/this.place#69]
**Description**
When pulling a block that is supposed to push the character off the ground, the character edges at the extreme corner of the ground block.

![image](https://user-images.githubusercontent.com/22815234/37268424-e58d0cb6-2600-11e8-9fba-87edfe8536ff.png)

**Replication of Bug**
1. Stand on an elevated block
2. Pull a block that should push the character off the block

**Comment by nicholaschuayunzhi** [comment]
Resolved in #109
