### ISSUE TITLE
Orthographic camera causing block clipping

### ISSUE THREAD

**Issue by teclu** [this-place/this.place#70]
![image](https://user-images.githubusercontent.com/27724529/37272264-1e7d1ce0-2611-11e8-8579-c8547e9f0398.png)

As discussed, the current Orthographic camera setup causes blocks to be clipped.

**Comment by nicholaschuayunzhi** [comment]
If we go with perspective camera as discussed in #71. We may not have to worry about this.

**Comment by nicholaschuayunzhi** [comment]
We're using perspective camera. Thus this won't be an issue.
