### ISSUE TITLE
Character Sprint/Run

### ISSUE THREAD

**Issue by teclu** [this-place/this.place#75]
Currently the character is only able to walk at a constant speed. This would slightly limit the platforming element(s) where players have to make a far jump across. Also, players may get tired of the walking speed (and want to speed things up, pun intended). Perhaps give the player a way to activate (or toggle) running, like holding the "shift" key.

**Comment by nicholaschuayunzhi** [comment]
Maybe we could just start with a simple acceleration for the character? The character must then find a way to build a run way for himself to traverse gaps.

**Comment by reginleiff** [comment]
@teclu Do you still think sprint is required with the upcoming camera changes? Did you re-design the tutorial stage with that in mind?

**Comment by nicholaschuayunzhi** [comment]
@reginleiff we recently merged a prototype run mechanic #88. You can try it out on master.
