### ISSUE TITLE
Blur objects that are near the screen

### ISSUE THREAD

**Issue by jo-lyn** [this-place/this.place#78]
Produces an effect like this:

![image](https://user-images.githubusercontent.com/30170203/37298693-f41981dc-265b-11e8-922b-8f3f9610dff0.png)

**Comment by nicholaschuayunzhi** [comment]
This looks cool, especially with a perspective camera. Is it easy to implement?

**Comment by jo-lyn** [comment]
Yep, just have to adjust depth of field in post processing!

![image](https://user-images.githubusercontent.com/30170203/37552936-5909f31a-29f9-11e8-8825-92fcb04af049.png)

We could try this out after the levels are done, in case the blurring will be annoying to the player.

**Comment by nicholaschuayunzhi** [comment]
Hi @jo-lyn i realised that with the current settings, the focus is on the objects near the camera and on the player. Are you able to resolve?
