### ISSUE TITLE
Gravel block uses texture of surrounding blocks

### ISSUE THREAD

**Issue by jo-lyn** [this-place/this.place#79]
Since we have particle effects for fragile blocks, we could consider letting gravel blocks take the texture of surrounding blocks so it blends well with the environment. The player will realise they are standing on a "gravel" block once they see the particles.

**Comment by nicholaschuayunzhi** [comment]
My concern that it may be too surprising for the player and he will have to restart the level. We may have to preempt the player before hand, maybe spawn particles here and there. When player steps on it, it will spawn more + shake abit.

**Comment by reginleiff** [comment]
@jo-lyn I think its a great idea to make environments more realistic though. Maybe we could try using an overlay effect over an existing block texture? For example, a transparent layer with cracks to give a feeling that "this block is unstable". Then the gravel block could have a drop down list in the inspector to select what kind of underlying texture we want.

**Comment by jo-lyn** [comment]
After looking at the levels, I think it could be best that we make the block distinct after all since the player needs to identify the block without accessing it to solve the puzzle. However, I'm trying to avoid a gravel texture as it might be similar to sand. I'm currently considering something woody (wooden crate?) which shouldn't look unnatural in the environment and gives the feeling of being fragile at the same time.
