### ISSUE TITLE
Feedback GDG 15 March

### ISSUE THREAD

**Issue by nicholaschuayunzhi** [this-place/this.place#80]
Collation of feedback from play testing during GDG session on 15 March 2018.

Here we will discuss what we can raise to potential issues. If you are unsure what these feedback mean, let me know.

# Feedback

## Camera
- [x] axis of motion feels weird (some feel that it is flipped)
- [x] many suggested a 3rd person camera (fortnite style), and block grab is for highlighted blocks in front of you
- [x] most if not all people were for perspective
    - [x] related #71 
- [x] camera motion (right click) is too sensitive

## Character
- [ ] jump to grab is hard to perform
- [x] click is pixel hunty (meaning that its hard to click on blocks, need to make clicking easier)
- [x] some suggested hold down button for a "to-grab" motion (this can be like a open arms pose) then release to actually grab
    - [x] this could help with the jump grab
- [ ] character motion/jump feels floaty
- [ ] character motion feels janky
    - [ ] unable to explain clearly but mentioned in general that it doesn't feel good enough
- [x] some suggested making our own cursor so that its more obvious that cursor is used in the game
- [x] difficult to judge distances, esp. 2nd jump in tutorial stage

## AI
*i talked to them about our two ai options, the sleeping block, and the random creeper*
- [ ] most people feel the sleeping block is a good idea
- [ ] random creeper was suggested also (without me prompting)

## Sand block
- [x] should not be top displace-able
- [ ] the gravity looks cool

## Invisible blocks
- [x] many felt that it looked good (we should work on it)

# Other Notes
- [x] we can have all levels in one scene, and chunk the levels to load (optimization)
- [ ] look into composite colliders
- [x] art style is good overall
- [ ] there's a shortcut in the tutorial level

**Comment by Rinder5** [comment]
if it's possible to chunk levels to load, can we use that for checkpoint functionality? (split level into checkpoint sized chunks, only load later parts of the stage if respawning at checkpoint, to keep back part the same)

**Comment by nicholaschuayunzhi** [comment]
so we don't load the back parts? even though its the same stage?

**Comment by teclu** [comment]
> click is pixel hunty (meaning that its hard to click on blocks, need to make clicking easier)

Since only the highlighted block is to be pulled, instead of using the mouse to click on it perhaps we can use a key instead (this was suggested by my friend this week).

**Comment by nicholaschuayunzhi** [comment]
> Since only the highlighted block is to be pulled, instead of using the mouse to click on it perhaps we can use a key instead (this was suggested by my friend this week).

can this tie in with this?

> some suggested hold down button for a "to-grab" motion (this can be like a open arms pose) then release to actually grab
this could help with the jump grab

**Comment by jo-lyn** [comment]
I think that having a key where we press and hold to grab could be more intuitive.
The player will continue to grab the block as long as they keep holding down the key, and release the block when they release the key.
If the player only taps on the key, the character will simply show a grabbing motion but will not grab anything since the key is released immediately.

On press = Grab motion
On release = Release motion?

**Comment by Rinder5** [comment]
edited the initial message to make it more readable

**Comment by Rinder5** [comment]
I think the rest of the outstanding issues are not relatable anymore to our current state of the game, and as such is no longer useful. Closing issue.
